#!/bin/bash

# Stash any unstaged changes
git stash -q --keep-index

# Running pnpm lint
echo "Running rome with bun and turbo ..."
pnpm lint

# If pnpm lint failed, stop the commit
if [ $? -ne 0 ]; then
  echo "pnpm lint failed, cancelling commit"
  git stash pop -q
  exit 1
fi

# Running black
echo "Running black ..."
poetry run black .

if [ $? -ne 0 ]; then
  echo "black failed, cancelling commit"
  git stash pop -q
  exit 1
fi

# Add any auto-fixes to the commit
echo "Adding lint fixes to commit..."
git add -u
